/**
 * Logo files for the curated client list, saved under public/logos/. Sources (Wikimedia Commons /
 * company websites) are recorded in public/logos/SOURCES.json. Trademarks belong to their owners; used
 * here only to preview a co-branded pitch for that client.
 */
export const KNOWN_CLIENT_LOGOS: Record<string, string> = {
  "danske": "/logos/danske.svg",
  "ing": "/logos/ing.svg",
  "rabobank": "/logos/rabobank.svg",
  "ubs": "/logos/ubs.png",
  "commerzbank": "/logos/commerzbank.svg",
  "deutsche-bank": "/logos/deutsche-bank.svg",
  "abn-amro": "/logos/abn-amro.svg",
  "natwest": "/logos/natwest.svg",
  "volkswagen": "/logos/volkswagen.svg",
  "mercedes-benz": "/logos/mercedes-benz.svg",
  "daimler-truck": "/logos/daimler-truck.svg",
  "bmw": "/logos/bmw.svg",
  "kone": "/logos/kone.svg",
  "toyota-europe": "/logos/toyota-europe.svg",
  "metsa": "/logos/metsa.png",
  "airbus": "/logos/airbus.svg",
  "volvo": "/logos/volvo.svg",
  "siemens": "/logos/siemens.svg",
  "hsbc": "/logos/hsbc.svg",
  "barclays": "/logos/barclays.svg",
  "lloyds": "/logos/lloyds.png",
  "standard-chartered": "/logos/standard-chartered.svg",
  "santander": "/logos/santander.svg",
  "bbva": "/logos/bbva.svg",
  "caixabank": "/logos/caixabank.svg",
  "bnp-paribas": "/logos/bnp-paribas.svg",
  "societe-generale": "/logos/societe-generale.svg",
  "credit-agricole": "/logos/credit-agricole.svg",
  "unicredit": "/logos/unicredit.svg",
  "intesa-sanpaolo": "/logos/intesa-sanpaolo.svg",
  "nordea": "/logos/nordea.svg",
  "seb": "/logos/seb.svg",
  "swedbank": "/logos/swedbank.svg",
  "dnb": "/logos/dnb.svg",
  "kbc": "/logos/kbc.svg",
  "erste": "/logos/erste.svg",
  "allianz": "/logos/allianz.svg",
  "axa": "/logos/axa.svg",
  "zurich": "/logos/zurich.svg",
  "generali": "/logos/generali.svg",
  "munich-re": "/logos/munich-re.svg",
  "aviva": "/logos/aviva.svg",
  "bosch": "/logos/bosch.svg",
  "continental": "/logos/continental.svg",
  "zf": "/logos/zf.svg",
  "schaeffler": "/logos/schaeffler.svg",
  "stellantis": "/logos/stellantis.svg",
  "renault": "/logos/renault.svg",
  "scania": "/logos/scania.svg",
  "man": "/logos/man.svg",
  "rolls-royce": "/logos/rolls-royce.svg",
  "safran": "/logos/safran.svg",
  "thales": "/logos/thales.svg",
  "leonardo": "/logos/leonardo.svg",
  "abb": "/logos/abb.svg",
  "schneider-electric": "/logos/schneider-electric.svg",
  "philips": "/logos/philips.svg",
  "nokia": "/logos/nokia.svg",
  "ericsson": "/logos/ericsson.svg",
  "basf": "/logos/basf.svg",
  "bayer": "/logos/bayer.svg",
  "sandvik": "/logos/sandvik.svg",
  "atlas-copco": "/logos/atlas-copco.svg",
  "heidelberg-materials": "/logos/heidelberg-materials.svg",
  "orsted": "/logos/orsted.svg",
  "vestas": "/logos/vestas.svg",
};

export function logoForKnownClient(id: string | undefined): string | undefined {
  return id ? KNOWN_CLIENT_LOGOS[id] : undefined;
}

/** Marker stored in clientLogoFileName when the logo came from the curated list rather than an upload. */
export const LIST_LOGO_MARKER = "(official logo from client list)";
